server.port: 8080

management:
  tracing:
    sampling.probability: 1
    baggage.enabled: true
    propagation: [B3]
    baggage:
      correlation:
        enabled: true
        fields:
          - valueToPropagate
      remote-fields:
        - valueToPropagate